include:
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.package-docker-image.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.sonarqube-check.yml'

stages:
  - build
  - code_quality
  - run_tests

.package:
  image: takamol/ci-cd:package-latest
  services:
    - name: docker:dind
  script:
    - echo $TAKAMOL_REGISTRY_PASSWORD | docker login -u $TAKAMOL_REGISTRY_USERNAME --password-stdin
    - docker pull $ENV_LATEST || true
    #remove --build-arg when pip registry will be ready
    - docker build --cache-from $ENV_LATEST --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg CI_SERVER_HOST=${CI_SERVER_HOST} -t $ENV_LATEST -t $VERSION_TAGGED .
    - docker push $ENV_LATEST
    - docker push $VERSION_TAGGED
    - echo "Image name $VERSION_TAGGED"

build:
  stage: build
  extends: .package
  tags:
    - oci-dind
  variables:
    ENV: master
  only:
      - merge_requests
      - schedules
      - web

robocop:
  image: takamol/svp_robot:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
  stage: code_quality
  tags:
    - oci-shared
  script:
    - cd /app
    - . $(find . -name activate)
    - poetry run robocop
  only:
    - merge_requests

pylint:
  stage: code_quality
  image: takamol/svp_robot:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
  tags:
    - oci-shared
  allow_failure: true
  before_script:
    - cd /app
    - . $(find . -name activate)
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
  script:
    - poetry run pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/svp-robot-*/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - poetry run pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/svp-robot-*/**") > codeclimate.json
    - poetry run pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/svp-robot-*/**") > public/lint/index.html
    - if [ $(cat public/badges/$CI_JOB_NAME.score) != 10.00 ]; then exit 1; fi
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
  only:
    - merge_requests

run_tests:
  image: takamol/svp_robot:master-latest
  allow_failure: true
  stage: run_tests
  tags:
    - oci-shared
  script:
    - cd /app
    - . ~/.bashrc
    - . $(find . -name activate)
    - python -m robot.run -d ./Results/Reports/ Tests/
  only:
    - merge_requests
    - schedules
    - web