from Resources.Variables import UserInfo

VALID_PASSWORD_LIST = [UserInfo.DEFAULT_PASSWORD, UserInfo.CHANGED_PASSWORD, UserInfo.CHANGED_PASSWORD]
INVALID_CURRENT_PASSWORD_LIST = [UserInfo.DEFAULT_PASSWORD + '1', UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD]
CURRENT_PASSWORD = [UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD]
MISMATCH_NEW_PASSWORD = [UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD + '1', UserInfo.DEFAULT_PASSWORD]
INVALID_CONFIRM_PASSWORD = [UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD, UserInfo.DEFAULT_PASSWORD + '1']
