from Resources.Variables import UserInfo, ErrorMessage

INVALID_LOGIN_DATASET = [UserInfo.INVALID_LOGIN, UserInfo.DEFAULT_PASSWORD, ErrorMessage.INVALID_CREDENTIALS]
INVALID_PASSWORD_DATASET = [UserInfo.DEFAULT_LOGIN, UserInfo.INVALID_PASSWORD, ErrorMessage.INVALID_CREDENTIALS]
