DASHBOARD_WELCOME_TEXT = 'Welcome to the Professional Accreditation Program Control Panel.'
ADMIN_CONFIRM_CODE = 'Two-Factor Verification'
CONFIRM_CODE = 'Two-Factor Verification'
LEGISLATOR_CREATION = {'type': 'legislator creation', 'text': 'The legislator has been created successfully'}
TEST_CENTER_CREATION = 'Test center has been created successfully'
TEST_CENTER_REMOVE = {'type': 'test center creation', 'text': 'Test Center has been deleted successfully'}
MESSAGE_VALID_CERTIFICATE = 'The certificate is valid'
MSG_CERTIFICATE = 'You can download list of certificates now'
SUCCESSFULLY_ACTIONS_CATEGORY = 'Category was updated'
SUCCESS_UPDATE_MESSAGE = 'Country has been updated successfully'
SUCCESS_UPDATE_CONTENT = 'Content has been successfully updated'
MSG_SUCCESS_ADD_OCCUPATION = 'success'
MSG_SUCCESS_UPLOAD_OCCUPATION = 'File has been uploaded successfully'
MSG_SUCCESS_INVITATION = 'Invitation link has been successfully sent'
