SIGN_IN = 'Sign in'
LEGISLATORS = 'Legislators'
NEW_LEGISLATOR = 'New Legislator'
NEW_TEST_CENTER = 'New Test Center'
TEST_CENTER = 'Test Centers'
SPA_SIGN_IN = 'Welcome to International SVP!'
SPA_SET_PASSWORD = 'Set Password'
CARD_DETAILS = {'type': 'header payment', 'text': 'PLEASE ENTER YOUR CARD DETAILS TO A PURCHASE'}
UPLOADED_FILES = 'Uploaded Files'
ADD_GROUP = {'type': 'modal', 'text': 'Add Group'}
TRANSACTION_HISTORY = {'type': 'spa', 'text': 'Transaction History'}
REPORTS = 'Reports'
CHECK_VALIDITY = 'Check Validity'
GROUP = {'type': 'spa', 'text': 'GROUP {}'}
PAYMENT_CONFIRMATION = {'type': 'spa', 'text': 'Payment Confirmation'}
PAYMENT = {'type': 'spa', 'text': 'Payment'}
ADD_INDIVIDUAL = {'type': 'modal', 'text': 'Add Individual'}
SPA_NEW_TEST_CENTER = {'type': 'spa', 'text': 'New Test Center'}
SPA_TEST_CENTER_INFORMATION = {'type': 'spa', 'text': 'Test Center Information'}
SPA_EDIT_TEST_CENTER = {'type': 'spa', 'text': 'EDIT TEST CENTER'}
SPA_ACCOUNT_INFORMATION = 'Account Information'
SPA_CHANGE_PASSWORD = 'Change Password'
SPA_PROFESSIONAL_ACCREDITATION_PROGRAM = 'Professional Accreditation Program'
TEST = {'selector': 'header', 'text': 'Welcome to International SVP!'}
