class AdminCategoriesLocators:
    CATEGORIES_TEXT = '//*[@id="app"]//h1'
    BTN_NEW_CATEGORY = '//*[@href="/categories/add"]'
    NEW_CATEGORY_TEXT = '//*[@id="app"]//h1'
    FIELD_CODE = '//*[@id="category_code"]'
    FIELD_ARABIC_NAME = '//*[@id="arabic_name"]'
    FIELD_ENGLISH_NAME = '//*[@id="english_name"]'
    FIELD_STATUS = '//*[@id="published"]'
    BTN_CREATE_CATEGORY = '//*[text()="Create Category"]'
    BTN_EDIT_CATEGORY = '//button[text() = "Edit Category"]'
    SUCCESSFULLY = '//*[@class="alert-message alert-message--success"]'
    ERROR_CODE = '//*[text()="Only digits"]'
    ERROR_ENGLISH_NAME = '//*[text()="Only english characters"]'
    ERROR_ARABIC_NAME = '//*[text()="Only arabic characters"]'
    LAST_ENTRY = 'tr:nth-child(1) td'
    LAST_ACTION = 'tr:nth-child(1) td[data-label="Actions"]'
    ICON_VIEW = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(1) a'
    ICON_EDIT = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(2) a'
    DATA_CATEGORY = '//*[@class="details-list__item"]'
    CHANGE_LOG_TEXT = '//*[text()="Change Logs"]'
    CHANGE_STATUS = '//*[@class="header-section__btn-wrap"]'
    BTN_UPLOAD_CATEGORIES = '//*[text()="Upload Categories"]'
    BTN_CHOOSE_FILE = '#upload_file'
    BTN_DONE = '//*[text()="Done"]'
    ERROR_DOWNLOAD = '//*[@class="validation-message__text validation-message__text--error mb-3"]'
    DOWNLOAD_CSV_SAMPLE = '//*[text()=" download csv sample "]'
