class AdminCountryLocators:
    BTN_ADD = '//*[text()="Add"]'
    BTN_NEW_COUNTRY = '//*[@href="/country/add"]'
    BTN_EDIT = '//*[text()="Edit"]'
    BTN_SEARCH = '//*[text()="Search"]'
    BTN_DEL = '//*[@class="multiselect__tag-icon"]'
    BTN_CANCEL = "//button[text() = 'Cancel']"
    PERMITTED_SERVICES_TEXT = '//*[@id="app"]//h1'
    COUNTRY = '//*[@id="country"]'
    NEW_COUNTRY_TEXT = '//*[@id="app"]//h1'
    LAST_ACTION = 'tr:nth-child(1) td[data-label="Actions"]'
    ICON_VIEW = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(1) a'
    ICON_EDIT = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(2) a'
    EDIT_COUNTRY = '//*[@id="app"]//h1'
    FIELDS_GROUP_EXPIRE_YEARS = '//*[@id="arabic_name"]'
    FIELD_MANDATED_DATE = '//*[@placeholder="dd-mm-yyyy"]'
    FIELD_NEW_TC = '//*[@id="name"]'
    CHECKBOX_CHECK = '//*[@class="checkbox__input test-center-check"]'
    CHECKBOX_GRAY = '//*[@class="checkbox__label text--regent-gray"]'
    CHECKBOX_LABEL = '//*[@class="text--regent-gray checkbox__label"]'
    CHECKBOX = '//*[@class="checkbox"]'
    CHECKBOX_CATEGORY = '//*[@class="checkbox checkbox--categories col-12 col-md-4 mt-0"]'
    RADIO_BUTTON = '//*[@class="input-group__wrapper "]//label'
    SELECT_NATIONALITY = '//*[@class="arrow"]'
    NATIONALITY = '//*[text()="Select Nationality"]/..//li//span//span'
    COUNTRY_SUCCESSFULLY_UPDATED = '//*[@class="alert-message alert-message--success"]'
    COUNTRY_CHOOSE_OPTION = '//*[@class="form-row"]//select'
    COUNTRY_TAB = 'tr:nth-child(1) td[data-label="Country"]'
    LEGISLATOR_TAB = 'tr:nth-child(1) td[data-label="Legislator"]'
    TCENTER_TAB = 'tr:nth-child(1) td[data-label="Test Center"]'
    LEGISLATOR = '//*[@id="legislator"]'
    TCENTER = '//*[@id="testCenter"]'
    LINKED_NATIONALITY = '//*[@class="toasted alert-msg-inner errors-nationalities toasted-primary error"]'
    NO_DATA = '//*[@class="table-no-data"]'
