class AdminLaborAttachesLocators:
    DEFAULT_COUNTRY = 'Algeria'
    LABOR_ATTACHES_TEXT = '//*[@id="app"]//h1'
    BTN_NEW_ATTACHE = '//button[text() = "New Attache"]'
    DROPDOWN_SELECT_COUNTRY = '//*[@class="q-page-box__content"]//*[@class="multiselect__select"]'
    SELECT_COUNTRY = f'//*[text()="{DEFAULT_COUNTRY}"]'
    FIELD_USER_EMAIL_ADDRESS = '//*[@id="user_email"]'
    BTN_SEND_INVITATION = '//button[text() = "Send Invitation"]'
    SUCCESS_SEND = '//*[@class="modal-form__heading"]'
    SUCCESS_BOX = '//*[@class="q-page-box__content"]'
    ERROR_SEND = '//*[@class="input-group input-group--margin-top"]//' \
                 'span[@class="validation-message__text validation-message__text--error"]'
    BTN_OK = '//button[text() = "ok"]'
    ADDED_EMAIL = 'tr:nth-child(1) td[data-label="Email"]'
    ICON_RESEND_ACTION = 'tr:nth-child(1) td[data-label="Actions"] li span'
    ICON_DOTS = 'tr:nth-child(1) td[data-label="Actions"]'
    BTN_YES = '//button[text() = "yes"]'
    FILTER_ICON = '//*[@class="filter-icon"]'
    BTN_APPLY = '//button[text() = "Apply"]'
    BTN_CLEAR = '//button[text() = "Clear"]'
    SELECT_COUNTRY_FILTER = '//*[@class="filter-form__body"]//*[@class="multiselect__select"]'
    SELECT_COUNTRY_TEXT = '//*[@class="filter-form__body"]//*[@class="input-group__label text--regent-gray "]'
    FILTER_CONTROL_TAG = '//*[@class="filter-controls__tag"]'
