class AdminCategoriesLocators:
    CATEGORIES_TEXT = '//*[@id="app"]//h1'
    BTN_NEW_CATEGORY = '//*[@href="/categories/add/details/edit"]'
    CATEGORY_INFORMATION_TEXT = '//*[@href="/categories/add/details"]'
    FIELD_CODE = '//*[@id="category_code"]'
    FIELD_ARABIC_NAME = '//*[@id="arabic_name"]'
    FIELD_ENGLISH_NAME = '//*[@id="english_name"]'
    FIELD_STATUS = 'select[name="published"]'
    FIELD_TEST_TYPE = 'select[name="examType"]'
    FIELD_PROMETRIC = '//*[@id="prometric_cbt_exam_weight"]'
    FIELD_WEIGHT = '//*[@id="cbt_exam_weight"]'
    FIELD_PROMETRIC_CODE = '//*[@id="prometric_code"]'
    BTN_SAVE_CATEGORY = '//*[text()="Save"]'
    SUCCESSFULLY = '//*[@class="toasted-container alert-msg top-center"]'
    ERROR_CODE = '//*[text()="Only digits"]'
    ERROR_ENGLISH_NAME = '//*[text()="Only english characters"]'
    ERROR_ARABIC_NAME = '//*[text()="Only arabic characters"]'
    LAST_ENTRY = 'tr:nth-child(1) td'
    LAST_ACTION = 'tr:nth-child(1) td[data-label="Actions"]'
    ICON_VIEW = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(1) a'
    ICON_EDIT = 'tr:nth-child(1) td[data-label="Actions"] li:nth-child(2) a'
    CHANGE_LOGS = '//*[text()=" Change Logs "]'
    BTN_UPLOAD_CATEGORIES = '//*[text()="Upload Categories"]'
    BTN_CHOOSE_FILE = '#upload_file'
    BTN_DONE = '//*[text()="Done"]'
    BTN_SAVE = '//*[text()="Save"]'
    ERROR_DOWNLOAD = '//*[@class="validation-message__text validation-message__text--error mb-3"]'
    DOWNLOAD_CSV_SAMPLE = '//*[text()=" download csv sample "]'
    DATA_CATEGORY = '//*[@class="info-value"]'
    PUBLISH_STATUS = '//*[@class="info-value"]//span'
    BTN_UNPUBLISH = '//button[text() = "Unpublish"]'
    BTN_PUBLISH = '//button[text() = "Publish"]'
    BTN_EDIT = '//*[text()="Edit"]'
    BTN_BACK = '//*[text()=" Back "]'
