class IndividualRegistrationLocators:
    FIELD_FIRST_NAME = '//*[@id="firstName"]'
    FIELD_LAST_NAME = '//*[@id="lastName"]'
    FIELD_NATIONAL_ID = '//*[@id="nationalId"]'
    FIELD_PASSPORT_NUMBER = '//*[@id="passportNumber"]'
    SELECT_COUNTRY_OF_RESIDENCE = '//*[text() = "Country of residence"]/../..//*[@class="multiselect__select"]'
    OPEN_COUNTRIES = '//*[text() = "Country of residence"]/../..//*[@class="multiselect__element"]/span/span'
    SELECT_NATIONALITY = '//*[text() = "Nationality"]/../..//*[@class="multiselect__select"]'
    OPEN_NATIONALITY = '//*[text() = "Nationality"]/../..//*[@class="multiselect__select"]' \
                       '/..//*[@class="multiselect__element"]/span'
    FIELD_EMAIL = '//*[@id="email"]'
    FIELD_DATE_OF_BIRTH = '//*[@placeholder="Enter your birth date"]'
    FIELD_PASSPORT_EXPIRATION = '//*[@placeholder="Enter passport expiration"]'
    FIELD_PASSWORD = '//*[@id="password"]'
    FIELD_CONFIRM_PASSWORD = '//*[@id="confirmPassword"]'
    CHECKBOX_ACKNOWLEDGE = 'label[for="confirm"]'
    BTN_CONTINUE = '//*[@id="continue_button2"]'
    PASSPORT_NUMBER_TEXT = '//*[@class="modal-form__sub-heading"]'
    BTN_CONFIRM_AND_PROCEED = '//button[text() = "Confirm and proceed"]'
