class IndividualBookingLocators:
    DEFAULT_OCCUPATION = '*****'
    DEFAULT_CITY = 'Kiev'
    BTN_BOOK_AN_APPOINTMENT = '//*[@href="/labor/booking/steps"]'
    BOOK_AN_APPOINTMENT_TEXT = '//*[@id="app"]//h1'
    BTN_SELECT_OCCUPATION = '//*[@class="input-group input-group--margin-small"]//*[@class="multiselect__select"]'
    SELECTED_OCCUPATION = f'//*[text()="{DEFAULT_OCCUPATION}"]'
    OCCUPATION_KEY = '//*[@class="step-item__description"]'
    DESCRIPTION_CATEGORY = '//*[@class="step-item__description-category"]'
    CHOOSE_CITY_TEXT = '//*[text()="Choose City"]'
    BTN_SELECT_CITY = '//*[@class="input-group input-group--margin-middle"]//*[@class="multiselect__select"]'
    SELECTED_CITY = f'//*[text()="{DEFAULT_CITY}"]'
    CHOOSE_DATE_TEXT = '//*[text()="Choose Date"]'
    CHOOSE_SESSION_TEXT = '//*[text()="Choose Session "]'
    SESSION_CARDS = '//*[@class="session-card__title"]'
    BTN_NEXT_INDIVIDUAL = '//*[@class="step-two"]//*[@class="btn btn--primary"]'
    SUMMARY_PAGE_TEXT = '//*[text()="Summary Page"]'
    CHECKBOX = 'label[for="accept"]'
    BTN_NEXT_SUMMARY = '//*[@class="btn btn--primary with-preloader no-space"]'
    BOOKED_APPOINTMENTS = '//*[@class="reservation-wrap"]//*[@class="row"]'
    EYE_ICON = '//*[@class="reservation-item__icon eye-icon"]'
    BOOKING_DETAILS_TEXT = '//*[@class="sidebar-item"]'
    DETAILS_VALUE = '//*[@class="details-value"]'
    ALREADY_RESERVATION = '//*[@class="modal-form__heading"]'
    BTN_INDIVIDUAL_OK = '//button[text() = "Ok"]'
    TRANSACTION_HISTORY_TEXT = '//*[@id="app"]//h2'
    FILTER_ICON = '//*[@class="filter-icon"]'
    TRANSACTION_LAST_ENTRY = 'tr:nth-child(1) td'
    BTN_APPLY = '//button[text() = "Apply"]'
    BTN_CLEAR_INDIVIDUAL_FILTER = '//button[text() = "Clear Filter"]'
    FILTER_FIELD_ID = '//*[@id="id"]'
    FILTER_FIELD_INVOICE_NUM = '//*[@id="invoice_num"]'
    FILTER_SELECT_STATUS = '//*[@class="multiselect__select"]'
    FILTER_FIELD_FROM = '//*[@placeholder="From"]'
    FILTER_FIELD_TO = '//*[@placeholder="To"]'
    FILTER_CONTROLS = '//*[@class="filter-controls__tag"]'
    DOWNLOAD_ICON = '//*[@href="#"]'
    HISTORY_ROW = 'tr[draggable]'
    TICKET_ICON = '//*[@class="reservation-item__icon ticket-icon"]'
    INDIVIDUAL_SUCCESS_ACTIONS = '//*[@class="reservation-item__icon ticket-icon"]/..'
    BTN_DOWNLOAD_TICKET = '//button[text() = " Download Ticket "]'
    FIELD_OCCUPATION = '//*[@id="occupationSearchSelect"]'
