LOGIN_FIELD = '#login_email'
PASSWORD_FIELD = '#login_password'
LOGIN_FORM = '.login-form__text.pb-3'
ERROR_MSG = '.validation-message--margin-bottom > span'
TWO_FA_FIELD = '#fk_1'
SIGN_IN_BUTTON = '.sign-form__button'
CAPCHA_FIELD = '.input-group__re-captcha'
OTP_CODE = '.otp-code'
OTP_CODE_WARNING_MSG = '.validation-message__text--error'
FORGOT_MY_PASSWORD = '//*[@href="/auth/forgot"]'
RESET_PASSWORD_TEXT = '//*[@id="app"]//h1'
FIELD_ENTER_EMAIL = 'input[name="email"]'
BTN_CONTINUE_RESET = '//*[@id="continue_button"]'
