class SPAAssessorsRegistration:
    BTN_PARTNERSHIP = '//*[@class="custom-dropdown__link"]'
    ITEM_REGISTERED_AS_ASSESSORS = '//*[text()="Register as Assessor"]'
    TEXT_REGISTER_INTO_SVP = '//*[text()="Register into SVP"]'
    FIELD_FULL_NAME = '//*[@id="fullName"]'
    FIELD_DATE_OF_BIRTH = '//*[@id="app"]//span/input'
    FIELD_CNIC = '//*[@id="nationalId"]'
    FIELD_PASSPORT_NUMBER = '//*[@id="passportNumber"]'
    FIELD_EMAIL = '//*[@id="email"]'
    FIELD_PHONE = '//*[@id="phoneNumber"]'
    DROPDOWN_GENDER = '//*[text()="Gender"]/../..//*[@class="multiselect__select"]'
    DROPDOWN_NATIONALITY = '//*[text()="Nationality"]/../..//*[@class="multiselect__select"]'
    AVAILABLE_NATIONALITIES = '//*[text()="Nationality"]/../..//*[@class="multiselect__element"]'
    DROPDOWN_CODE = '//*[@class="vti__dropdown-arrow"]'
    AVAILABLE_CODES = '//*[@class="vti__dropdown-item"]'
    BTN_PASSPORT_FILE = '//*[text()="Attach your passport copy or photo"]/..//*[@class="uploader-block"]'
    BTN_CONTINUE = '//*[@id="continue_button2"]'
    DROPDOWN_COUNTRY = '//*[text()="Country"]/../..//*[@class="multiselect__select"]'
    DROPDOWN_CITY = '//*[text()="City"]/../..//*[@class="multiselect__select"]'
    TEXT_CITY = '//*[text()="City"]'
    DROPDOWN_CATEGORY = '//*[text()="Category"]/../..//*[@class="multiselect__select"]'
    TEXT_CATEGORY = '//*[text()="Category"]'
    DROPDOWN_LANGUAGES = '//*[text()="Which Languages you know?"]/../..//*[@class="multiselect__select"]'
    TEXT_LANGUAGES = '//*[text()="Which Languages you know?"]'
    BTN_QUALIFICATIONS_FILE = '//*[text()="Upload qualifications"]/../..//*[@class="browse"]'
    BTN_EXPERIENCE_FILE = '//*[text()="Upload Experience Certificate"]/../..//*[@class="browse"]'
    FIELD_INSTITUTE_NAME = '//*[@id="instituteName"]'
    BTN_BACK = '//button[text() = "Back"]'
    BTN_CHECK_CERTIFICATE_AND_EXAM_RESULT = '//button[text() = "Check certificate & exam result"]'
    FIELD_CONFIRM = '//*[contains(text(),"Agree on ")]'
    TEXT_TERMS_OF_USE = '//*[@id="app"]//h1'
    BTN_SUBMIT_REQUEST = '//button[text() = "Submit Request"]'
    ERROR_FIELD_EMAIL = '//*[text()="Email"]/../..' \
                        '//*[@class="validation-message__text validation-message__text--error"]'
    ERROR_FIELD_CNIC = '//*[text()="CNIC (National ID)"]/../..' \
                       '//*[@class="validation-message__text validation-message__text--error"]'
