class SPAAssessorsLocators:
    BTN_ASSESSORS = '//*[@href="/assessors-list"]'
    ASSESSORS_TEXT = '//*[@class="q-page-box__header"]'
    ACTIONS = '//*[@class="actions-wrap"]'
    ICON_VIEW_ACTION = '//*[@class="actions-dropdown"]//*[text()=" View "]'
    DATA = '//*[@class="details-value"]'
    ADDRESS = '//*[text()="Address"]'
    OTHER_DETAILS = '//*[text()="Other Details"]'
    BTN_BACK = '//*[@class="btn back"]'
    COUNTRY = '//*[text()="Country"]'
    CATEGORY = '//*[text()="Category"]'
    VIEW_PASSPORT = '//*[text()="View passport"]'
    LICENSES_CERTIFICATIONS = '//*[text()="Licenses & Certifications"]'
    EXPERIENCE = '//*[text()="Experience certificate"]'
    FILTER = '//*[@class="filter-icon"]'
    FIELD_NAME = '//*[@placeholder="Full Name"]'
    FIELD_CNIC = '//*[@placeholder="CNIC"]'
    FIELD_PHONE_NUMBER = '//*[@id="phoneNumber"]'
    FIELD_PASSPORT_NUMBER = '//*[@placeholder="Passport Number"]'
    FIELD_FROM = '//*[@placeholder="From"]'
    FIELD_TO = '//*[@placeholder="To"]'
    FIELD_EXAM_SESSION_STATUS = ''
    BTN_APPLY = '//button[text() = "Apply"]'
    BTN_CLEAR_FILTER_ASSESSORS = '//button[text() = "Clear Filter"]'
    CHECK_FILTER = '//*[@class="filter-controls__tag"]'
    ENTRY = 'td[data-label]'
    DROP = '//*[@class="multiselect__select"]'
