TOGGLE_SHOW_LOGO = 'div:nth-child(2) > ul > li:nth-child(2) > div'
ADDRESS = 'div:nth-child(2) > ul > li:nth-child(3) > div'
POSTAL_CODE = 'div:nth-child(2) > ul > li:nth-child(4) > div'
FULL_NAME = 'div:nth-child(4) > ul > li:nth-child(1) > div'
PHONE_NUMBER = 'div:nth-child(4) > ul > li:nth-child(2) > div'
EMAIL = 'div:nth-child(4) > ul > li:nth-child(3) > div'

BTN_EDIT = '//button[.="Edit"]'
BTN_SAVE = '//button[.="Save"]'
BTN_CANCEL = '//button[.="Cancel"]'

BTN_LOGO_FILE = '#logo'
TOGGLE_EDIT_SHOW_LOGO = '.switch'
TOGGLE_STATUS = '.switch input'
FIELD_ADDRESS = '#address'
FIELD_POSTAL_CODE = '#postal_code'
FIELD_FULL_NAME = '#full_name'
FIELD_PHONE_NUMBER = '#phone_number'
FIELD_EMAIL = '#email'

WARNING_POSTAL_CODE = '//input[@id="postal_code"]/parent::div/following-sibling::div/span/span'
WARNING_NAME = '//input[@id="full_name"]/parent::div/following-sibling::div/span/span'
WARNING_PHONE_NUMBER = '//input[@id="phone_number"]/parent::div/following-sibling::span'
WARNING_EMAIL = '//input[@id="email"]/parent::div/following-sibling::div/span/span'
