class SPAExamSessionLocators:
    BTN_EXAM_SESSION = '//*[@href="/exam-sessions"]'
    EXAM_SESSION_TEXT = '//*[text()="Exam Sessions"]'
    BTN_ADD_SESSION = '//*[@class="item-add__btn"]'
    TIME_FROM = '//*[text()="From"]'
    TIME_TO = '//*[text()="To"]'
    SEATS = '//*[text()="Choose Number"]'
    CHOOSE_CATEGORY = '//*[@class="multiselect__placeholder"]'
    REPEAT_SESSION = '//*[@class="multiselect__tags"]//*[text()="Does not repeat"]'
    INPUT_TIME_FROM = '//*[@placeholder="From"]'
    INPUT_TIME_TO = '//*[@placeholder="To"]'
    INPUT_SEATS = '//*[@placeholder="Choose Number"]'
    CATEGORY_SESSION = "//span[contains(text(),'Engine Mechanics')]"
    BTN_ADD = '//*[text()="Add"]'
    BTN_OK = '//*[text()="Ok"]'
    SESSION_CATEGORY = '//*[@class="session__category"]'
    SESSION_TIME = '//*[@class="session__time"]'
    SESSION_SEATS = '//*[@class="session__seats"]'
    SESSION_STATUS = '//*[@class="status-label status-label--scheduled"]'
    SESSION_SEE_MORE = '//*[@class="session__btn btn"]'
    TEXT_ERROR = '//*[@class="text-error"]'
    SESSION_ENTRY = '//*[@class="details-value"]'
